"""
Streamlit interface to visualize and compare DMITS (baseline) and PROPOSED scheduler results.

This app reads the CSV / text outputs produced by `main.py` and presents:
- High-level summary metrics for each scheduler
- Per-trial comparison plots (success rate, delay, completed tasks)
- The final bar-chart image already generated by `plot_with_error_bars`
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import streamlit as st


RESULTS_DIR = Path("results")
TRIAL_RESULTS_CSV = RESULTS_DIR / "trial_results.csv"
SUMMARY_TXT = RESULTS_DIR / "summary.txt"
COMPARISON_PNG = RESULTS_DIR / "comparison_results.png"


def load_csv(path: Path) -> pd.DataFrame | None:
    if not path.exists():
        return None
    return pd.read_csv(path)


def main() -> None:
    st.set_page_config(
        page_title="Scheduler Comparison: DMITS vs Proposed",
        layout="wide",
    )

    st.title("Scheduler Comparison: **DMITS** vs **PROPOSED**")
    st.write(
        "This interface visualizes the results generated by `main.py`, "
        "comparing the baseline **DMITS** scheduler with the **Proposed** scheduler."
    )

    with st.sidebar:
        st.header("Instructions")
        st.markdown(
            "- Ensure you have run `python main.py` at least once so that the "
            "`results/` folder is populated.\n"
            "- Use the sections on this page to explore high-level metrics, "
            "per-trial performance, and the final comparison chart."
        )

    # Load all available outputs
    trial_df = load_csv(TRIAL_RESULTS_CSV)
    summary_text = SUMMARY_TXT.read_text(encoding="utf-8") if SUMMARY_TXT.exists() else None

    if trial_df is None:
        st.error(
            f"Could not find `{TRIAL_RESULTS_CSV}`.\n\n"
            "Please run `python main.py` in your project directory to generate the results."
        )
        return

    # Normalize scheduler labels to be consistent
    trial_df["scheduler"] = trial_df["scheduler"].str.upper()

    st.subheader("High-level Summary")
    cols = st.columns(2)

    # Always compute aggregated statistics directly from `trial_results.csv`
    with cols[0]:
        st.markdown("**Aggregated metrics (computed from `trial_results.csv`)**")
        agg = (
            trial_df.groupby("scheduler")
            .agg(
                success_mean=("success_rate", "mean"),
                success_std=("success_rate", "std"),
                delay_mean=("avg_delay", "mean"),
                delay_std=("avg_delay", "std"),
                completed_mean=("completed_tasks", "mean"),
            )
            .reset_index()
        )
        st.dataframe(agg, use_container_width=True)

    with cols[1]:
        if summary_text:
            st.markdown("**Text summary (`summary.txt`)**")
            st.text(summary_text)
        else:
            st.info("No `summary.txt` file found.")

    st.markdown("---")
    st.subheader("Per-trial Comparison")

    metric = st.selectbox(
        "Metric to compare per trial",
        options=["success_rate", "avg_delay", "completed_tasks", "total_time"],
        format_func=lambda x: {
            "success_rate": "Success Rate (%)",
            "avg_delay": "Average Delay (s)",
            "completed_tasks": "Completed Tasks",
            "total_time": "Total Time (s)",
        }[x],
    )

    # Pivot data to have DMITS and PROPOSED side-by-side for each trial
    if "trial" in trial_df.columns:
        pivot = trial_df.pivot_table(
            index="trial",
            columns="scheduler",
            values=metric,
        )

        st.line_chart(pivot, use_container_width=True)

        st.markdown("**Raw per-trial data**")
        st.dataframe(trial_df.sort_values(["trial", "scheduler"]), use_container_width=True)
    else:
        st.warning("The `trial_results.csv` file does not contain a `trial` column.")
        st.dataframe(trial_df, use_container_width=True)

    st.markdown("---")
    st.subheader("Final Comparison Chart")

    if COMPARISON_PNG.exists():
        st.image(str(COMPARISON_PNG), caption="Scheduler Comparison (DMITS vs Proposed)", use_column_width=True)
    else:
        st.info(f"No `{COMPARISON_PNG.name}` image found in the `results/` directory.")


if __name__ == "__main__":
    main()


